---
abstract: 'lightweight yet powerful web application framework'
author:
  - 'Dancer Core Developers'
build_requires:
  Devel::Hide: 0
  Digest::MD5: 0
  ExtUtils::MakeMaker: 0
  File::Spec: 0
  HTTP::Cookies: 0
  HTTP::Request: 0
  IO::Handle: 0
  IPC::Open3: 0
  Plack::Builder: 0
  Test::More: 0
  Test::NoWarnings: 0
  blib: 1.01
  perl: 5.006
  utf8: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.040, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer
provides:
  Dancer:
    file: lib/Dancer.pm
    version: 1.3202
  Dancer::App:
    file: lib/Dancer/App.pm
    version: 1.3202
  Dancer::Config:
    file: lib/Dancer/Config.pm
    version: 1.3202
  Dancer::Config::Object:
    file: lib/Dancer/Config/Object.pm
    version: 1.3202
  Dancer::Continuation:
    file: lib/Dancer/Continuation.pm
    version: 1.3202
  Dancer::Continuation::Halted:
    file: lib/Dancer/Continuation/Halted.pm
    version: 1.3202
  Dancer::Continuation::Route:
    file: lib/Dancer/Continuation/Route.pm
    version: 1.3202
  Dancer::Continuation::Route::ErrorSent:
    file: lib/Dancer/Continuation/Route/ErrorSent.pm
    version: 1.3202
  Dancer::Continuation::Route::FileSent:
    file: lib/Dancer/Continuation/Route/FileSent.pm
    version: 1.3202
  Dancer::Continuation::Route::Forwarded:
    file: lib/Dancer/Continuation/Route/Forwarded.pm
    version: 1.3202
  Dancer::Continuation::Route::Passed:
    file: lib/Dancer/Continuation/Route/Passed.pm
    version: 1.3202
  Dancer::Continuation::Route::Templated:
    file: lib/Dancer/Continuation/Route/Templated.pm
    version: 1.3202
  Dancer::Cookie:
    file: lib/Dancer/Cookie.pm
    version: 1.3202
  Dancer::Cookies:
    file: lib/Dancer/Cookies.pm
    version: 1.3202
  Dancer::Deprecation:
    file: lib/Dancer/Deprecation.pm
    version: 1.3202
  Dancer::Engine:
    file: lib/Dancer/Engine.pm
    version: 1.3202
  Dancer::Error:
    file: lib/Dancer/Error.pm
    version: 1.3202
  Dancer::Exception:
    file: lib/Dancer/Exception.pm
    version: 1.3202
  Dancer::Exception::Base:
    file: lib/Dancer/Exception/Base.pm
    version: 1.3202
  Dancer::Factory::Hook:
    file: lib/Dancer/Factory/Hook.pm
    version: 1.3202
  Dancer::FileUtils:
    file: lib/Dancer/FileUtils.pm
    version: 1.3202
  Dancer::GetOpt:
    file: lib/Dancer/GetOpt.pm
    version: 1.3202
  Dancer::HTTP:
    file: lib/Dancer/HTTP.pm
    version: 1.3202
  Dancer::Handler:
    file: lib/Dancer/Handler.pm
    version: 1.3202
  Dancer::Handler::Debug:
    file: lib/Dancer/Handler/Debug.pm
    version: 1.3202
  Dancer::Handler::PSGI:
    file: lib/Dancer/Handler/PSGI.pm
    version: 1.3202
  Dancer::Handler::Standalone:
    file: lib/Dancer/Handler/Standalone.pm
    version: 1.3202
  Dancer::Hook:
    file: lib/Dancer/Hook.pm
    version: 1.3202
  Dancer::Hook::Properties:
    file: lib/Dancer/Hook/Properties.pm
    version: 1.3202
  Dancer::Logger:
    file: lib/Dancer/Logger.pm
    version: 1.3202
  Dancer::Logger::Abstract:
    file: lib/Dancer/Logger/Abstract.pm
    version: 1.3202
  Dancer::Logger::Capture:
    file: lib/Dancer/Logger/Capture.pm
    version: 1.3202
  Dancer::Logger::Capture::Trap:
    file: lib/Dancer/Logger/Capture/Trap.pm
    version: 1.3202
  Dancer::Logger::Console:
    file: lib/Dancer/Logger/Console.pm
    version: 1.3202
  Dancer::Logger::Diag:
    file: lib/Dancer/Logger/Diag.pm
    version: 1.3202
  Dancer::Logger::File:
    file: lib/Dancer/Logger/File.pm
    version: 1.3202
  Dancer::Logger::Note:
    file: lib/Dancer/Logger/Note.pm
    version: 1.3202
  Dancer::Logger::Null:
    file: lib/Dancer/Logger/Null.pm
    version: 1.3202
  Dancer::MIME:
    file: lib/Dancer/MIME.pm
    version: 1.3202
  Dancer::ModuleLoader:
    file: lib/Dancer/ModuleLoader.pm
    version: 1.3202
  Dancer::Object:
    file: lib/Dancer/Object.pm
    version: 1.3202
  Dancer::Object::Singleton:
    file: lib/Dancer/Object/Singleton.pm
    version: 1.3202
  Dancer::Plugin:
    file: lib/Dancer/Plugin.pm
    version: 1.3202
  Dancer::Plugin::Ajax:
    file: lib/Dancer/Plugin/Ajax.pm
    version: 1.3202
  Dancer::Renderer:
    file: lib/Dancer/Renderer.pm
    version: 1.3202
  Dancer::Request:
    file: lib/Dancer/Request.pm
    version: 1.3202
  Dancer::Request::Upload:
    file: lib/Dancer/Request/Upload.pm
    version: 1.3202
  Dancer::Response:
    file: lib/Dancer/Response.pm
    version: 1.3202
  Dancer::Route:
    file: lib/Dancer/Route.pm
    version: 1.3202
  Dancer::Route::Cache:
    file: lib/Dancer/Route/Cache.pm
    version: 1.3202
  Dancer::Route::Registry:
    file: lib/Dancer/Route/Registry.pm
    version: 1.3202
  Dancer::Serializer:
    file: lib/Dancer/Serializer.pm
    version: 1.3202
  Dancer::Serializer::Abstract:
    file: lib/Dancer/Serializer/Abstract.pm
    version: 1.3202
  Dancer::Serializer::Dumper:
    file: lib/Dancer/Serializer/Dumper.pm
    version: 1.3202
  Dancer::Serializer::JSON:
    file: lib/Dancer/Serializer/JSON.pm
    version: 1.3202
  Dancer::Serializer::JSONP:
    file: lib/Dancer/Serializer/JSONP.pm
    version: 1.3202
  Dancer::Serializer::Mutable:
    file: lib/Dancer/Serializer/Mutable.pm
    version: 1.3202
  Dancer::Serializer::XML:
    file: lib/Dancer/Serializer/XML.pm
    version: 1.3202
  Dancer::Serializer::YAML:
    file: lib/Dancer/Serializer/YAML.pm
    version: 1.3202
  Dancer::Session:
    file: lib/Dancer/Session.pm
    version: 1.3202
  Dancer::Session::Abstract:
    file: lib/Dancer/Session/Abstract.pm
    version: 1.3202
  Dancer::Session::Simple:
    file: lib/Dancer/Session/Simple.pm
    version: 1.3202
  Dancer::Session::YAML:
    file: lib/Dancer/Session/YAML.pm
    version: 1.3202
  Dancer::SharedData:
    file: lib/Dancer/SharedData.pm
    version: 1.3202
  Dancer::Template:
    file: lib/Dancer/Template.pm
    version: 1.3202
  Dancer::Template::Abstract:
    file: lib/Dancer/Template/Abstract.pm
    version: 1.3202
  Dancer::Template::Simple:
    file: lib/Dancer/Template/Simple.pm
    version: 1.3202
  Dancer::Template::TemplateToolkit:
    file: lib/Dancer/Template/TemplateToolkit.pm
    version: 1.3202
  Dancer::Test:
    file: lib/Dancer/Test.pm
    version: 1.3202
  Dancer::Timer:
    file: lib/Dancer/Timer.pm
    version: 1.3202
recommends:
  YAML: 0
requires:
  Carp: 0
  Cwd: 0
  Data::Dumper: 0
  Encode: 0
  Exporter: 0
  Fcntl: 0
  File::Basename: 0
  File::Copy: 0
  File::Path: 0
  File::Spec: 0
  File::Spec::Functions: 0
  File::Temp: 0
  File::stat: 0
  FindBin: 0
  Getopt::Long: 0
  HTTP::Body: 0
  HTTP::Date: 0
  HTTP::Headers: 0
  HTTP::Server::Simple::PSGI: 0
  Hash::Merge::Simple: 0
  IO::File: 0
  LWP::UserAgent: 0
  MIME::Types: 0
  Module::Runtime: 0
  POSIX: 0
  Pod::Usage: 0
  Scalar::Util: 0
  Test::Builder: 0
  Test::More: 0
  Time::HiRes: 0
  Try::Tiny: 0
  URI: 0
  URI::Escape: 0
  base: 0
  bytes: 0
  constant: 0
  lib: 0
  overload: 0
  parent: 0
  strict: 0
  vars: 0
  warnings: 0
resources:
  bugtracker: https://github.com/PerlDancer/Dancer/issues
  homepage: https://github.com/PerlDancer/Dancer
  repository: https://github.com/PerlDancer/Dancer.git
version: 1.3202
x_authority: cpan:SUKRIA
x_contributors:
  - 'a-adam <ac@univie.ac.at>'
  - 'Adam J. Foxson <afoxson@pobox.com>'
  - 'Adam Kennedy <adamk@cpan.org>'
  - 'Akash Ayare <akash@hairynandgate.com>'
  - 'alambike <alambike@gmail.com>'
  - 'Alan Haggai Alavi <alanhaggai@alanhaggai.org>'
  - 'Alberto Simoes <ambs@cpan.org>'
  - 'Alberto Simões <ambs@cpan.org>'
  - 'Alessandro Ranellucci <aar@cpan.org>'
  - 'Alex C <calyx238@gmail.com>'
  - 'Alexis Sukrieh <sukria@sukria.net>'
  - 'Alex Kalderimis <alex.kalderimis@gmail.com>'
  - 'Alex Kapranoff <kapranoff@gmail.com>'
  - 'Alex Peters <lxp@cpan.org>'
  - 'Alfie John <alfiej@opera.com>'
  - 'Al Newkirk <github@alnewkirk.com>'
  - 'Al Newkirk <we@ana.im>'
  - 'Andrew Beverley <a.beverley@ctrlo.com>'
  - 'andy <andy@broadbean.com>'
  - 'Anirvan Chatterjee <anirvan@base.mx.org>'
  - 'Anton Gerasimov <me@zyxmasta.com>'
  - 'asergei <asergei@gmail.com>'
  - 'Ashley Willis <ashley@gitable.org>'
  - 'A. Sinan Unur <nanis@cpan.org>'
  - 'Ask Bjørn Hansen <ask@develooper.com>'
  - 'Assaf Gordon <assafgordon@gmail.com>'
  - 'Ben Hutton <relequestual@gmail.com>'
  - 'Bernhard Reutner-Fischer <rep.dot.nop@gmail.com>'
  - 'boris shomodjvarac <shomodj@oginwm09.(none)>'
  - 'Brad Macpherson <brad@teched-creations.com>'
  - 'brian <brian@massassi.com>'
  - 'Brian E. Lozier <brian@massassi.com>'
  - 'Brian Hann <emailc0bra@gmail.com>'
  - 'Brian Phillips <brian@thephillips.info>'
  - 'Chris Andrews <chrisandrews@venda.com>'
  - 'Chris Seymour <chris.j.seymour@hotmail.com>'
  - 'Christian Walde <walde.christian@googlemail.com>'
  - 'chromatic <chromatic@wgz.org>'
  - 'Colin Keith <colinmkeith@gmail.com>'
  - 'Colin Kuskie <colink@perldreamer.com>'
  - 'CPAN Service <cpanservice@chorny.net>'
  - 'Craig Treptow <craig.treptow@gmail.com>'
  - 'Dagfinn Ilmari Mannsåker <ilmari@ilmari.org>'
  - 'Damien Krotkine <dams@cpan.org>'
  - 'Danijel Tasov <dt@korn.shell.la>'
  - 'Dave Doyle <dave.s.doyle@gmail.com>'
  - 'David Cantrell <david@cantrell.org.uk>'
  - 'David Golden <dagolden@cpan.org>'
  - 'David Moreno <david@axiombox.com>'
  - 'David Precious <davidp@preshweb.co.uk>'
  - 'David Steinbrunner <dsteinbrunner@pobox.com>'
  - 'David Zurborg <zurborg@cpan.org>'
  - 'Dennis Lichtenthaeler <dennis.lichtenthaeler@stiftung-tannenhof.de>'
  - 'Duncan Hutty <dhutty@allgoodbits.org>'
  - 'Emmanuel Rodriguez <emmanuel.rodriguez@gmail.com>'
  - 'Fabrice Gabolde <fabrice.gabolde@gmail.com>'
  - 'Fabrice Gabolde <fabrice.gabolde@uperto.com>'
  - 'Fabrice Gabolde <fgabolde@weborama.com>'
  - 'Fayland Lam <fayland@gmail.com>'
  - 'Felix Dorner <felix_do@web.de>'
  - 'Flavio Poletti <flavio@polettix.it>'
  - 'Florian Larysch <florolf@devbraindump.de>'
  - 'Florian Sojer <sojer@b1-systems.de>'
  - 'Franck Cuny <franck.cuny@gmail.com>'
  - 'franck cuny <franck.cuny@gmail.com>'
  - 'François Charlier <fcharlier@ploup.net>'
  - 'François Charlier <naz@pwah.(none)>'
  - 'Gabor Szabo <gabor@szabgab.com>'
  - 'Gary Mullen <garymullen@gmail.com>'
  - 'geistteufel <geistteufel@yahoo.fr>'
  - 'Grzegorz Rożniecki <xaerxess@gmail.com>'
  - 'Hagen Fuchs <github@hfuchs.net>'
  - 'Hans Dieter Pearcey <hdp@weftsoar.net>'
  - 'Ilmari Vacklin <ilmari@dicole.com>'
  - 'Ilya Chesnokov <chesnokov.ilya@gmail.com>'
  - 'isync <o.zucker@web.de>'
  - 'Ivan Bessarabov <ivan@bessarabov.ru>'
  - 'Ivan Paponov <ivan.paponov@gmail.com>'
  - 'Jacob Rideout <jacob.rideout@returnpath.net>'
  - 'Jakob Voss <jakob@nichtich.de>'
  - 'James Aitken <loonypandora@gmail.com>'
  - 'jamhed <ip@ncom-ufa.ru>'
  - 'jamhed <jamhed@lenobook.jh>'
  - 'jamhed.nb <ip@ncom-ufa.ru>'
  - 'Jesse van Herk <jesse@imaginaryrobots.net>'
  - 'Jochen Lutz <jlu@gmx.de>'
  - 'Joel Roth <joelz@pobox.com>'
  - 'John Barrett <johna.barrett@gmail.com>'
  - 'John Wittkoski <jwittkoski@gmail.com>'
  - 'jonasreinsch <jonas.reinsch@gmail.com>'
  - "Jonathan \"Duke\" Leto <jonathan@leto.net>"
  - 'Jonathan Hall <jhall@efolder.net>'
  - 'Jonathan Otsuka <djgoku@gmail.com>'
  - 'jonathan schatz <jon@divisionbyzero.com>'
  - 'Jonathan Scott Duff <duff@pobox.com>'
  - 'Joshua Barratt <jbarratt@serialized.net>'
  - 'JT Smith <jt@plainblack.com>'
  - 'Juan J. Martínez <reidrac@usebox.net>'
  - 'Jury Gorky <schwein@schwein-laptop.(none)>'
  - 'Kaitlyn Parkhurst <symkat@symkat.com>'
  - 'Kent Fredric <kentnl@cpan.org>'
  - 'Kirk Kimmel <kimmel.k.programmer@gmail.com>'
  - 'Lars Thegler <lars@thegler.dk>'
  - 'Lee Carmichael <lecar_red@yahoo.com>'
  - 'Lee Johnson <lee.johnson@netbanx.com>'
  - 'LoonyPandora <loonypandora@gmail.com>'
  - 'Manuel Weiss <manuel@weiss.io>'
  - 'Marc Chantreux <marc.chantreux@biblibre.com>'
  - 'Mark Allen <mrallen1@yahoo.com>'
  - 'Mark A. Stratman <stratman@gmail.com>'
  - 'Mark Stosberg <mark@stosberg.com>'
  - 'Martin Schut <github@wommm.nl>'
  - 'Matthew Horsfall (alh) <wolfsage@gmail.com>'
  - 'Maurice <mauricemengel@gmail.com>'
  - 'Maxim Ivanov <maxim.ivanov@net-a-porter.com>'
  - 'Max Maischein <corion@corion.net>'
  - 'Michael Genereux <mgenereu@gmail.com>'
  - 'Michael G. Schwern <schwern@pobox.com>'
  - 'Michal Wojciechowski <michal@sidnet.info>'
  - 'Mikolaj Kucharski <mikolaj@kucharski.name>'
  - 'miyagawa <miyagawa@gmail.com>'
  - 'mokko <mauricemengel@gmail.com>'
  - 'Murray <murray@minty.org>'
  - 'Natal Ngétal <hobbestigrou@erakis.im>'
  - 'Nate Jones <nate@endot.org>'
  - 'Naveed Massjouni <naveedm9@gmail.com>'
  - 'Naveed Massjouni <naveed@vt.edu>'
  - 'Naveed <naveed@ironcamel.(none)>'
  - 'Naveen <nmani@nashresearch.com>'
  - 'Neil Hooey <neil@shutterstock.com>'
  - 'Nicolas Oudard <noudard@weborama.com>'
  - 'niko <nikomomo@gmail.com>'
  - 'Nuno Carvalho <mestre.smash@gmail.com>'
  - 'Oliver Gorwits <oliver@cpan.org>'
  - 'Olivier Mengué <dolmen@cpan.org>'
  - 'Olof Johansson <olof@ethup.se>'
  - 'Ovid <curtis@weborama.com>'
  - 'Paul Driver <frodwith@gmail.com>'
  - 'Paul Fenwick <pjf@perltraining.com.au>'
  - 'Paul Johnson <paul@pjcj.net>'
  - 'Paul Tomlin <ptomli@gmail.com>'
  - 'pdl <perrettdl@googlemail.com>'
  - 'Pedro Melo <melo@simplicidade.org>'
  - 'Perlover <perlover@perlover.com>'
  - 'Philippe Bruhat (BooK) <book@cpan.org>'
  - 'Richard Simões <rsimoes@cpan.org>'
  - 'Rick Myers <rick@jrmyers.net>'
  - 'Rik Brown <rik@rikbrown.co.uk>'
  - 'Roberto Patriarca <rp@staged.org>'
  - 'Roman Galeev <ip@ncom-ufa.ru>'
  - 'Roman Nuritdinov <ky6uk.kun@gmail.com>'
  - 'Rowan Thorpe <rowanthorpe@gmail.com>'
  - 'rowanthorpe <rowanthorpe@gmail.com>'
  - 'Russell Jenkins <veryrusty@gmail.com>'
  - 'Sam Kington <github@illuminated.co.uk>'
  - 'Sawyer X <xsawyerx@cpan.org>'
  - 'scoopio <valiouk@yahoo.co.uk>'
  - 'sdeseille <sebastien.deseille@gmail.com>'
  - 'Sebastian de Castelberg <sebu@kpricorn.org>'
  - 'sebastian de castelberg <sebu@kpricorn.org>'
  - 'Skeeve <github.mails.skeeve@xoxy.net>'
  - 'Slaven Rezic <slaven@rezic.de>'
  - 'smashz <mestre.smash@gmail.com>'
  - 'Sniperovitch <sniperovitch@gmail.com>'
  - 'Squeeks <squeek@cpan.org>'
  - 'Stefan Hornburg (Racke) <racke@linuxia.de>'
  - 'Steve Hay <steve.m.hay@googlemail.com>'
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
  - 'Tim King <timk@JTimothyKing.com>'
  - 'Tom Heady <tom@punch.net>'
  - 'Tom Hukins <tom@eborcom.com>'
  - 'Tom Wyant <wyant@cpan.org>'
  - 'Vyacheslav Matyukhin <mmcleric@yandex-team.ru>'
  - 'William Wolf <throughnothing@gmail.com>'
  - 'Xaerxess <xaerxess@gmail.com>'
  - 'Yanick Champoux <yanick@cpan.org>'
  - 'YOUR_NAME <YOUR_EMAIL>'
